export const ERROR_CODES = {
  // Auth Errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // Resource Errors
  NOT_FOUND: 'NOT_FOUND',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  RECOVERY_NOT_FOUND: 'RECOVERY_NOT_FOUND',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',

  // Regulatory & Business Rules
  NPCI_LIMIT_REACHED: 'NPCI_LIMIT_REACHED',
  NPCI_COOLDOWN_ACTIVE: 'NPCI_COOLDOWN_ACTIVE',
  TERMINAL_BANK_FAILURE: 'TERMINAL_BANK_FAILURE',
  CUSTOMER_OPTED_OUT: 'CUSTOMER_OPTED_OUT',
  DISCOUNT_FLOOR_EXCEEDED: 'DISCOUNT_FLOOR_EXCEEDED',
  RECOVERY_ALREADY_RESOLVED: 'RECOVERY_ALREADY_RESOLVED',

  // External / Gateway
  RAZORPAY_SIGNATURE_INVALID: 'RAZORPAY_SIGNATURE_INVALID',
  RAZORPAY_API_ERROR: 'RAZORPAY_API_ERROR',
  AI_PROCESSING_ERROR: 'AI_PROCESSING_ERROR',
  NOTIFICATION_FAILED: 'NOTIFICATION_FAILED',

  // System
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;
