export const RECOVERY_STATUSES = {
  ANALYZING_AI: 'ANALYZING_AI',
  SCHEDULED_RETRY: 'SCHEDULED_RETRY',
  PAYMENT_LINK_SENT: 'PAYMENT_LINK_SENT',
  RETRY_IN_PROGRESS: 'RETRY_IN_PROGRESS',
  RECOVERED_AUTO_DEBIT: 'RECOVERED_AUTO_DEBIT',
  RECOVERED_VIA_LINK: 'RECOVERED_VIA_LINK',
  STOP_NPCI_LIMIT_REACHED: 'STOP_NPCI_LIMIT_REACHED',
  STOP_TERMINAL_FAILURE: 'STOP_TERMINAL_FAILURE',
  STOP_CUSTOMER_OPTED_OUT: 'STOP_CUSTOMER_OPTED_OUT',
  STOP_DISCOUNT_FLOOR_EXCEEDED: 'STOP_DISCOUNT_FLOOR_EXCEEDED',
  STOP_MANUAL_CANCELLED: 'STOP_MANUAL_CANCELLED',
} as const;

export type RecoveryStatusType = keyof typeof RECOVERY_STATUSES;

export const RECOVERY_TYPES = {
  SUBSCRIPTION_AUTOPAY: 'SUBSCRIPTION_AUTOPAY',
  CHECKOUT_ABANDONMENT: 'CHECKOUT_ABANDONMENT',
} as const;

export type RecoveryType = keyof typeof RECOVERY_TYPES;

export const TERMINAL_RECOVERY_STATUSES: string[] = [
  RECOVERY_STATUSES.RECOVERED_AUTO_DEBIT,
  RECOVERY_STATUSES.RECOVERED_VIA_LINK,
  RECOVERY_STATUSES.STOP_NPCI_LIMIT_REACHED,
  RECOVERY_STATUSES.STOP_TERMINAL_FAILURE,
  RECOVERY_STATUSES.STOP_CUSTOMER_OPTED_OUT,
  RECOVERY_STATUSES.STOP_DISCOUNT_FLOOR_EXCEEDED,
  RECOVERY_STATUSES.STOP_MANUAL_CANCELLED,
];

export const ACTIVE_RECOVERY_STATUSES: string[] = [
  RECOVERY_STATUSES.ANALYZING_AI,
  RECOVERY_STATUSES.SCHEDULED_RETRY,
  RECOVERY_STATUSES.PAYMENT_LINK_SENT,
  RECOVERY_STATUSES.RETRY_IN_PROGRESS,
];
